#version 460
#pragma scheduler(OBE)
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_KHR_shader_subgroup_vote : enable

layout(local_size_x = 4) in;
layout(tla_subgroup_size = 2) in;
layout(tla_num_workgroups = 1) in;
layout(tla_synchronization_id = 4) in; // 0=None, 1=SSO, 2=SCF, 3=SM, 4=CM


layout(std430, binding = 0) buffer Partition {
    uint part;
};

void main() {
    part = gl_SubgroupInvocationID;
    uint read = atomicLoad(part, 4, 64, 0);
    assert(subgroupAllEqual(read));
}
