#version 460
#pragma scheduler(OBE)
#extension GL_KHR_memory_scope_semantics : enable

layout(local_size_x = 2) in;
layout(tla_subgroup_size = 2) in;
layout(tla_num_workgroups = 1) in;
layout(tla_synchronization_id = 3) in; // SM

layout(std430, binding = 0) buffer Partition {
    uint slots[2];
};

void main() {
    uint tid = gl_LocalInvocationID.x;

    atomicStore(slots[tid], tid + 1u, 4, 64, 0);
    uint read = atomicLoad(slots[tid], 4, 64, 0);

    assert(read == tid + 1u);
}
