#version 460
#pragma scheduler(OBE)
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_memory_scope_semantics : enable

layout(local_size_x = 2) in;
layout(tla_subgroup_size = 2) in;
layout(tla_num_workgroups = 1) in;
layout(tla_synchronization_id = 2) in; // 0=None, 1=SSO, 2=SCF, 3=SM, 4=CM

layout(std430, binding = 0) buffer Partition {
    uint slots[2];
};

void main() {
    uint tid = gl_LocalInvocationID.x;
    uint next = (tid + 1u) % 2u;

    atomicStore(slots[next], 1u, 4, 64, 0);
    uint read = 0u;
    if ((tid % 2u) == 0u) {
        read = atomicLoad(slots[tid], 4, 64, 0);
    } else {
        read = atomicLoad(slots[tid], 4, 64, 0);
    }

    subgroupBarrier();
    assert(read == 1u);
}
